#!/bin/bash

function unary_gate {
    cat <<EOF

  component $1_gate
    port (
      x : in std_logic;
      z : out std_logic
    );
  end component $1_gate;

  component $1_gate_n
    generic (
      n : integer
    );
    port (
      x : in std_logic_vector(n-1 downto 0);
      z : out std_logic_vector(n-1 downto 0)
    );
  end component $1_gate_n;

  component $1_gate_32
    port (
      x : in std_logic_vector(31 downto 0);
      z : out std_logic_vector(31 downto 0)
    );
  end component $1_gate_32;
EOF
}

function binary_gate {
    cat <<EOF

  component $1_gate
    port (
      x : in std_logic;
      y : in std_logic;
      z : out std_logic
    );
  end component $1_gate;

  component $1_gate_n
    generic (
      n : integer
    );
    port (
      x : in std_logic_vector(n-1 downto 0);
      y : in std_logic_vector(n-1 downto 0);
      z : out std_logic_vector(n-1 downto 0)
    );
  end component $1_gate_n;

  component $1_gate_32
    port (
      x : in std_logic_vector(31 downto 0);
      y : in std_logic_vector(31 downto 0);
      z : out std_logic_vector(31 downto 0)
    );
  end component $1_gate_32;
EOF
}

cat <<EOF
-- This file is generated by automatic tools.
EOF

cat <<EOF
library ieee;
use ieee.std_logic_1164.all;
EOF

cat <<EOF
package eecs361_gates is
EOF

unary_gate not
binary_gate and
binary_gate or
binary_gate nand
binary_gate nor
binary_gate xor
binary_gate xnor

cat <<EOF
end;
EOF
