-- This file is generated by automatic tools.
library ieee;
use ieee.std_logic_1164.all;

entity %GATE%_gate_n is
  generic (
    n   : integer
  );
  port (
    x   : in  std_logic_vector(n-1 downto 0);
    z   : out std_logic_vector(n-1 downto 0)
  );
end %GATE%_gate_n;

architecture dataflow of %GATE%_gate_n is
begin
  z <= %GATE% x;
end dataflow;
